### ISSUE TITLE
Add a section regarding the significance of various MESSAGE files.

### ISSUE THREAD

**Issue by hbshrestha** [SPLATteam/splat-tutorial#11]
It is relevant to add a section describing the significance of various MESSAGE files such as *`.adb`, `*.ldb`, `*.mps`, `*.tab`, `*.lpsol` files, etc. to understand what happens in the backend while running SPLAT model. Important aspects to make note are in which stages are these files created, what are their significance and usage.

Manual for MESSAGE: "C:\Users\HShrestha\International Renewable Energy Agency - IRENA\EPS - PTG Tools and Data\MESSAGE\MessageV.pdf" (also attached herewith)

## Databases in MESSAGE program

|Acronyms|Full form|Significance|
|-----------|----------|-------------|
|adb|Application database|adb file is created and maintained for each case study. It contains information on default scenario created by MESSAGE. For a new case study, it is appropriate to work on its adb rather than creating a scenario and working on an ldb. |
|ldb|Local database|ldb file is created and maintained for each (alternative) scenario in a case study. It is a copy of adb file. It is created for each alternative scenario, which user can modify as per their scenario narratives. When input sheets (parameters) are updated in SPLAT for alternative scenario, the corresponding ldb files also get updated.|
|tdb|Technology database|tdb file is created and maintained independent of any case study|
|upd|Update database|upd file is created and maintained to update values in the adb and/or a set of scenarios in a case study across the board.|

![image](https://user-images.githubusercontent.com/50154485/209341901-6736cdc0-97d8-4602-b81b-a6239ac6b06a.png)

## Significance of various files
|Folder|File|Full form|Significance|
|-------|----|---------|-------------|
|data|Region.adb and Region_Casename.ldb|Application database; Local database|The data folder contains the required files for loading into the model. The adb file contains the model description and all information about technologies and their characterisitics for the default scenario in the model. The ldb file contains relevant data for default scenario as well as alternative scenarios in the model. These files are loaded into Excel memory by pressing the `Reload Global` button. |
|data|Region.tit|Title file|This is **not** a standard MESSAGE file. This file is added by IRENA in the SPLAT model directory. It carries hourly profiles of all the technologies that have been configured in the model to have time slice wise capacity factors. |
|data|Region_Casename.ldr|Load regions file|It contains information on load curves defined across various seasons in the model. |
|intm (interim folder) |Region_Casename.mps|Mathematical Programming System|The mps file contains the optimization problem (model objective and constraints) in a solver readable format. Mathematically, the problem is represented in matrix notation. These files are created by running the model with `MXG` in the Report-Annual sheet in the model. `MXG` is a Python script that converts .adb or .ldb file into .mps file. |
|intm|Region_Casename_lin.sol|Linear Solution|This file is created by running the model with either of these solvers: CPLEX, CBC, or Gurobi. The file carries solution of the problem in form of human readable format text but is still not in MESSAGE readable format.|
|data|Region.cin|Cap Input file| SPLAT prepares this file before running the MESSAGE CAP utility. Parameters, whose results are required to be extracted, must be filled into corresponding cells in ReportGen-Annual sheet. CAP is a utility available in MESSAGE GUI package.​|
|res|Region_Casename.toc|Table of Contents file|This file carries headers of all result tables extracted by MESSAGE CAP utility. |
|res|Region_Casename.tab|Tabular format file|The MESSAGE CAP utility extracts results from the .sol file in the interim folder in a tabular format. This file is required to `Get Results` from SPLAT. Main reasons for empty .tab file could be that the .cin file is empty or could not be created appropriately. |

Note:
- `Region` could refer to an acronym for a country e.g., `ZAa` for SouthAfrica or a continent i.e., `MAINa`.
- `CaseName` refers to a scenario.
- `MXG` and `CAP` are utility scripts for translating file types within the MESSAGE GUI application.

@bhussain89, I think it's worth having a section with a brief explanation of the various MESSAGE files, and what do they signify when they appear in the model folder after running the SPLAT model. What do you think?
Could you provide information on the significance of data, intm, and res folders? Are the significance of the MESSAGE files and databases I mentioned above, correct? Could you provide information where I have left blank? Are there any additional files that we should highlight or include?

[MessageV.pdf](https://github.com/lys1900/splat-tutorial/files/10295248/MessageV.pdf)

**Comment by bhussain89** [comment]
I have prepared some initial shape of flow chart 'SPLAT process and file': https://irena.sharepoint.com/:p:/s/EPS/EU9kbm1lTitCmzFMzCsHXc4B8thCc8oGTQRG2QNt_qg78g?e=Ow7JSB

Placed here:**EPS - General Tools and Data\SPLAT Interface and Database\20221227 web documentation\01 SPLAT process and files**

**Comment by hbshrestha** [comment]
@lys1900 We need to create a placefolder section in the documentation to include the flowchart and description of MESSAGE files as provided above.

**Comment by hbshrestha** [comment]
Yunshu to continue working on it. To get feedback from modellers regarding the appropriate placeholder section in the documentation.

**Comment by hbshrestha** [comment]
@lys1900 I was able to add csv files as tables in the web documentation ([example](https://splat-tutorial--19.org.readthedocs.build/en/19/MESSAGE.html)). However, I am not able to fix the height of the table rows. Perhaps, this can be fixed in the css [theme](https://github.com/SPLATteam/splat-tutorial/blob/main/docs/_static/css/splat_interface.css).

**Comment by hbshrestha** [comment]
Added the contents including SPLAT MESSAGE workflow diagram [here](https://splat-tutorial.readthedocs.io/en/test_csv_table/MESSAGE.html).
