### ISSUE TITLE
Rename a heading 

### ISSUE THREAD

**Issue by bhussain89** [SPLATteam/splat-tutorial#38]
Current heading 3.7 shown below is misleading. Need to review the structure again. Or as quick thing, we can just rename it like 'Defining technologies'

![image](https://github.com/SPLATteam/splat-tutorial/assets/77098670/1ff2ff01-a5b1-4e2d-8c1e-7dc89a81ca4f)

**Comment by hbshrestha** [comment]
Renamed as "Defining VRE and storage technologies".
![image](https://github.com/SPLATteam/splat-tutorial/assets/50154485/62a9e358-34fc-481d-b2c8-eae6bec3ef44)

**Comment by bhussain89** [comment]
Hi. Thanks but just to note that Dam based Hydropower tech is neither storage nor VRE.
